apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: location
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- common-dataset-pvc.yaml
- keco-import-job.yaml
- db-bootstrap-job.yaml
- common-dataset-build-job.yaml
- common-dataset-import-job.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: ecoeco-backend
    domain: location
    tier: business-logic
