apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: chat-

resources:
  - ../../base

images:
  - name: ghcr.io/sesacthon/placeholder
    newName: ghcr.io/sesacthon/chat
    newTag: latest

patches:
  - path: deployment-patch.yaml

commonLabels:
  domain: chat
  phase: "3"

