apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: my
spec:
  template:
    spec:
      containers:
      - name: my-api
        env:
        - name: POSTGRES_HOST
          value: dev-postgresql.postgres.svc.cluster.local
