apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../components/alb-controller/prod
  - ../components/external-secrets/prod
  - ../components/rabbitmq-operator/prod
  - ../components/redis-operator/prod
  - ../components/postgres-operator/prod
  - ../components/prometheus-operator/prod

