apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: my
images:
- name: docker.io/mng990/eco2
  newTag: my-worker-1.0.7-114705
commonLabels:
  environment: prod
replicas:
- name: my-worker
  count: 2
