apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
- ../base
- ../network-policies  # commonLabels 적용 제외 (ECK Pod 라벨 호환)

commonLabels:
  environment: dev
