apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service-accounts.yaml
- cluster-roles.yaml
- cluster-rolebindings.yaml
- namespaced-roles.yaml
- namespaced-rolebindings.yaml
- storage-class.yaml
