apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: scan-

resources:
  - ../../base

images:
  - name: ghcr.io/sesacthon/placeholder
    newName: ghcr.io/sesacthon/scan
    newTag: latest

patches:
  - path: deployment-patch.yaml

commonLabels:
  domain: scan
  phase: "1"

