apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: info-

resources:
  - ../../base

images:
  - name: ghcr.io/sesacthon/placeholder
    newName: ghcr.io/sesacthon/info
    newTag: latest

patches:
  - path: deployment-patch.yaml

commonLabels:
  domain: info
  phase: "3"

