apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NetworkPolicy는 commonLabels 적용 제외
# ECK가 생성한 Pod 라벨(common.k8s.elastic.co/type)만 사용

namespace: logging

resources:
- network-policy.yaml
