apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../components/alb-controller/dev
  - ../components/external-secrets/dev
  - ../components/rabbitmq-operator/dev
  - ../components/postgres-operator/dev
  - ../components/prometheus-operator/dev

