apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: api-ingress
      namespace: default
    path: patch-api-ingress.json
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: argocd-ingress
      namespace: argocd
    path: patch-argocd-ingress.json
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: grafana-ingress
      namespace: monitoring
    path: patch-grafana-ingress.json
