apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rabbitmq/cluster-operator/v1.11.0/config/manager/manager.yaml
patchesStrategicMerge:
  - manager-patch.yaml
images:
  - name: rabbitmqoperator/cluster-operator-dev
    newName: rabbitmqoperator/cluster-operator
    newTag: 1.11.0

