apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: location-

resources:
  - ../../base

images:
  - name: ghcr.io/sesacthon/placeholder
    newName: ghcr.io/sesacthon/location
    newTag: latest

patches:
  - path: deployment-patch.yaml

commonLabels:
  domain: location
  phase: "2"

