apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:123456789012:certificate/DEV_API_CERT
    external-dns.alpha.kubernetes.io/hostname: api.dev.ecoeco.app
spec:
  rules:
    - host: api.dev.ecoeco.app

