apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat
resources:
- ../base
patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: chat-worker
- path: patch-configmap.yaml
  target:
    kind: ConfigMap
    name: chat-worker-config
images:
- name: docker.io/mng990/eco2
  newTag: chat-worker-dev-latest
commonLabels:
  environment: dev
