apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api
namePrefix: my-

resources:
  - ../../base

images:
  - name: ghcr.io/sesacthon/placeholder
    newName: ghcr.io/sesacthon/my
    newTag: latest

patches:
  - path: deployment-patch.yaml

commonLabels:
  domain: my
  phase: "1"

