apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  generators:
  - list:
      elements:
      - name: auth
        namespace: auth
      - name: argocd
        namespace: argocd
      - name: grafana
        namespace: grafana
  template:
    metadata:
      name: dev-ingress-{{name}}
      namespace: argocd
    spec:
      project: dev
      source:
        repoURL: https://github.com/eco2-team/backend.git
        targetRevision: develop
        path: workloads/ingress/{{name}}/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

