apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-platform-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: dev
  source:
    repoURL: https://github.com/eco2-team/backend.git
    targetRevision: develop
    path: workloads/ingress/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

