apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-grpc
  namespace: auth
  labels:
    app: auth-grpc
    tier: business-logic
    domain: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-grpc
  template:
    metadata:
      labels:
        app: auth-grpc
        tier: business-logic
        domain: auth
    spec:
      containers:
      - name: auth-grpc
        image: docker.io/mng990/eco2:auth-api-dev-latest
        imagePullPolicy: Always
        command: [python, -m, domains.auth.rpc.server]
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: AUTH_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: AUTH_DATABASE_URL
        - name: AUTH_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: AUTH_REDIS_URL
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secret
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: dockerhub-secret
      nodeSelector:
        domain: auth
      tolerations:
      - key: domain
        operator: Equal
        value: auth
        effect: NoSchedule
