apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: calico-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - list:
        elements:
          - env: dev
            project: dev
            namespace: tigera-operator
            valueFile: platform/helm/calico/values/dev.yaml
          - env: prod
            project: prod
            namespace: tigera-operator
            valueFile: platform/helm/calico/values/prod.yaml
  template:
    metadata:
      name: "{{env}}-calico"
      namespace: argocd
    spec:
      project: "{{project}}"
      sources:
        - repoURL: https://docs.tigera.io/calico/charts
          chart: tigera-operator
          targetRevision: v3.27.0
        - repoURL: https://github.com/SeSACTHON/backend.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      helm:
        releaseName: calico
        valueFiles:
          - "$values/{{ valueFile }}"

