apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: platform
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts
    chart: redis-operator
    targetRevision: 0.22.2
    helm:
      releaseName: redis-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: data-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

