apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
commonLabels:
  app.kubernetes.io/part-of: ecoeco-backend
  tier: business-logic
  domain: chat

