apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/main/config/crd/bases/redis.redis.opstreelabs.in_redis.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/main/config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/main/config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/main/config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml


