apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: auth
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "base"
  AUTH_FRONTEND_URL: "https://frontend-beta-gray-c44lrfj3n1.vercel.app"
  AUTH_JWT_ALGORITHM: "HS256"
  AUTH_JWT_ISSUER: "eco2-auth"
  AUTH_JWT_AUDIENCE: "eco2-clients"
  AUTH_ACCESS_TOKEN_EXP_MINUTES: "15"
  AUTH_REFRESH_TOKEN_EXP_MINUTES: "20160"

